// In this file you can specify the trial data for your experiment


const trial_info = {
    practiceKeyPress: [
      {
          question: "same or different?",
          picture: 'mental_rotation_images/1_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "1",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/1_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "1",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/1_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "1",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/1_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "1",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/2_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "2",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/2_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "2",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/2_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "2",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/2_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "2",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/3_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "3",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/3_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "1",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/3_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "3",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/3_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "1",
          degreeOfRotation: "50"
      }
    ],
    keyPress: [
      {
          question: "same or different?",
          picture: 'mental_rotation_images/4_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "4",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/4_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "1",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/4_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "4",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/4_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "4",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/5_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "5",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/5_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "5",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/5_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "5",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/5_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "5",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/6_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "6",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/6_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "6",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/6_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "6",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/6_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "6",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/7_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "7",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/7_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "7",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/7_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "7",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/7_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "7",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/8_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "8",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/8_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "8",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/8_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "8",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/8_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "8",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/9_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "9",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/9_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "9",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/9_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "9",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/9_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "9",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/10_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "10",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/10_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "10",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/10_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "10",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/10_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "10",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/11_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "11",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/11_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "11",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/11_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "11",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/11_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "11",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/12_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "12",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/12_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "12",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/12_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "12",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/12_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "12",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/13_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "13",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/13_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "13",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/13_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "13",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/13_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "13",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/14_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "14",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/14_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "14",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/14_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "14",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/14_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "14",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/15_50_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "15",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/15_50_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "15",
          degreeOfRotation: "50"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/15_150_different.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"different",
          numberOfPic: "15",
          degreeOfRotation: "150"
      },
      {
          question: "same or different?",
          picture: 'mental_rotation_images/15_150_same.jpg',
          key1: 's',
          key2: 'd',
          s: 'same',
          d: "different",
          expected:"same",
          numberOfPic: "15",
          degreeOfRotation: "150"
      }
    ]
};
